from NeteaseCloudMusic.upload import upload
from NeteaseCloudMusic.login import login
from NeteaseCloudMusic.addSongToSonglist import addSongToSonglist
from NeteaseCloudMusic.getSongListDetail import getSongListDetail
from NeteaseCloudMusic.getUserSongLists import getUserSongLists
from NeteaseCloudMusic.uploadCorrection import uploadCorrection